<?php
/**
 * Page Pattern: Buckeye
 *
 * This file contains the complete page data for the 'Buckeye' page.
 * It can be imported to create/update the page on other environments.
 *
 * Includes: Content, Featured Image, Status, Attributes, Custom Fields
 *
 * To use: Tools → Page Content Sync → Import All Pages from Files
 *
 * @package CustomTheme
 */

return array(
	'title'               => 'Buckeye',
	'slug'                => 'buckeye-personal-injury-lawyer',
	'status'              => 'publish',
	'excerpt'             => '',
	'parent_slug'         => '',
	'menu_order'          => 0,
	'template'            => '',
	'featured_image_url'  => '',
	'featured_image_path' => '', // Theme assets path (ships via Git)
	'custom_fields'       => array(),
	'content'             => <<<'EOD'
<!-- wp:mbn-theme/hero-section {"eyebrowText":"Locations","mainHeading":"Buckeye Personal Injury Lawyer","subheading":"At Hastings & Hastings, we understand the profound impact a personal injury can have on your life. As compassionate Buckeye, AZ, personal injury attorneys, we are dedicated to fighting for your rights and securing the compensation you rightfully deserve.\n<br/><br/>\nIf you have been harmed in Buckeye due to someone else’s negligence or intentional wrongdoing. Let us be your guiding light on the road to recovery.","badgeImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-90-plus-combined-legal-experience.svg","badgeImageId":9897,"videoMp4Url":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.mp4","videoMp4Id":417,"videoWebmUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.webm","videoWebmId":416,"overlayImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-fg-video-overlay-1.webp","overlayImageId":9912,"showCtaBar":false,"contentJustify":"justify-between","contentVerticalAlign":"items-end","textMaxWidth":"max-w-3xl"} /-->

<!-- wp:mbn-theme/section-location-intro {"title":"Why Choose Hastings & Hastings As Your Buckeye Personal Injury Attorney","introParagraph":"<a href="/west-valley-personal-injury-lawyer/">Choosing the right West Valley attorney</a> is crucial when facing injuries and losses resulting from a personal injury. Hastings &amp; Hastings offers unparalleled expertise and client-focused services to ensure you receive the best possible outcome. We have extensive <a href="/buckeye-wrongful-death-attorney/">experience in wrongful death cases</a>, <a href="/buckeye-pedestrian-accident-lawyer/">pedestrian accident cases</a> and more.","sections":[{"type":"fee-structure","badgeImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-no-fee-until-win.svg","badgeImageId":9917,"subtitle":"No Win, No Fee","paragraph":"We handle personal injury cases on a contingency fee basis, meaning you pay nothing unless we win your case."},{"type":"track-record","subtitle":"Client Satisfaction","paragraph":"Always with an experienced, licensed Arizona personal injury attorney.","stats":[{"number":"600+","label":"Real, Handwritten Reviews"},{"number":"500+","label":"Five-star Google reviews from verified, actual past clients."}]},{"type":"track-record","subtitle":"Proven Success","paragraph":"Over 90 years of combined legal experience and a strong track record of successful settlements.","stats":[{"number":"90+","label":"combined legal experience"}],"columnPosition":"text-right"},{"type":"attorneys","subtitle":"Free Initial Consultation","paragraph":"Always with an experienced, licensed Arizona personal injury attorney.","teamImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-location-hastings-attorneys.jpg","teamImageId":10769}],"ctaBackgroundImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-bg-cta-column-scaled.jpg","ctaBackgroundImageId":10765,"ctaLogoUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-logo-hh.svg","ctaLogoId":442} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"heading":"Understanding Personal Injury Cases in Arizona","introParagraphs":["A personal injury occurs when someone suffers harm due to another’s negligence or intentional actions. At Hastings & Hastings, we handle a wide range of personal injury cases, including:"],"listStyle":"two-column","listItems":[{"title":"Economic Damages","description":"To cover quantifiable losses such as medical expenses, lost wages, and property damage.","label":"Car Accident Injuries","url":"/practice-areas/auto-accident-injuries/"},{"title":"Non-economic Damages","description":"To compensate for subjective, non-monetary losses like pain, suffering, and emotional distress.","label":"Burn Accidents","url":"/phoenix-burn-injury-lawyer/"},{"title":"Punitive Damages","description":"In some cases, a court may award you punitive damages if the at-fault party's conduct was particularly egregious, serving as a punishment and deterrent for such behavior.","label":"Bicycle Accidents","url":"/practice-areas/bicycle-accidents/"},{"title":"","description":"","label":"Catastrophic Injury","url":"/practice-areas/serious-catastrophic-injuries/"},{"title":"","description":"","label":"Construction Accidents","url":"/practice-areas/serious-catastrophic-injuries/"},{"title":"","description":"","label":"Dog Bites and Attacks","url":"/practice-areas/dog-bites/"},{"title":"","description":"","label":"Motorcycle Accidents","url":"/practice-areas/motorcycle-accidents/"},{"title":"","description":"","label":"Pedestrian Accidents","url":"/practice-areas/phoenix-pedestrian-accident-attorney/"},{"title":"","description":"","label":"Premises Liability Claims","url":"/phoenix-premises-liability-lawyer/"},{"title":"","description":"","label":"Truck Accidents","url":"/practice-areas/truck-accident-lawyer/"},{"title":"","description":"","label":"Slip and Fall Accidents","url":"/practice-areas/slip-falls/"},{"title":"","description":"","label":"Wrongful Death Claims","url":"/practice-areas/wrongful-death/"}],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-understanding-personal-injury-cases.jpg","imageId":10747,"footerParagraphs":["The consequences of a personal injury can be devastating, affecting you and your loved ones physically, emotionally, and financially. Fair compensation is essential to cover your medical bills, lost wages, and other damages.","However, insurance companies are notorious for doing whatever they can to minimize their payouts. Personal injury claimants represented by an experienced attorney typically recover significantly more compensation than those who go it alone."]} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"backgroundColor":"bg-white","heading":"How Liability for a Personal Injury is Established in Arizona","introParagraphs":["Various parties can be held liable for a personal injury in Arizona, depending on the circumstances of the accident. These can include:"],"listItems":[{"title":"Individuals","description":"Such as a <a href="/buckeye-car-accident-lawyer/">driver who caused a car accident</a>.","label":"","url":""},{"title":"Employers","description":"If an employee caused you harm while acting within the scope of their employment.","label":"","url":""},{"title":"Medical Professionals and Institutions","description":"If medical malpractice is involved.","label":"","url":""},{"title":"Manufacturers and Distributors","description":"Companies that produce or distribute dangerous or defective products.","label":"","url":""},{"title":"Property Owners","description":"If unsafe conditions on someone else’s property led to you being harmed.","label":"","url":""},{"title":"Government Entities","description":"Such as when an injury results from defective road conditions or a police shooting.","label":"","url":""}],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-how-liability-for-personal-injury.jpg","imageId":10746,"footerParagraphs":["Establishing liability involves proving negligence, which requires showing that the defendant owed a duty of care, breached that duty, and caused you harm. The experienced Buckeye, AZ, personal injury attorneys at Hastings & Hastings are skilled not only in identifying all liable parties and establishing liability in personal injury cases but also in navigating the complex legal landscape to ensure your best interests are protected."]} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-compensation.jpg","imageId":10745} /-->

<!-- wp:mbn-theme/section-location-text-image {"rows":[{"heading":"The Statute of Limitations for Personal Injury Claims in Arizona","paragraphs":["In Arizona, a personal injury claim must be filed within two years from the date of the injury (<a href="https://www.azleg.gov/ars/12/02505.htm" target="_blank" rel="noopener">A.R.S. § 12-542</a>). This timeframe can be shortened or extended based on specific circumstances, such as when the injured party is a minor, or the defendant is a government entity.","It is essential to consult with a knowledgeable attorney to protect your right to bring a lawsuit. Your attorney can also help you initiate an insurance claim to address your immediate needs and negotiate a settlement before a lawsuit needs to be filed."],"listItems":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-statute-of-limitation.jpg","imageId":10736,"imagePosition":"right"},{"heading":"How Hastings & Hastings Can Help","paragraphs":["Hastings & Hastings offers comprehensive legal support for personal injury cases in Buckeye, AZ. Our services include:"],"listItems":["A thorough case evaluation","Assistance with gathering evidence","Negotiation with the liable insurance companies","Representation in court, if necessary","A discounted fee structure, meaning more compensation for you."],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-how-hastings-n-hastings-can-help.jpg","imageId":10741,"imagePosition":"left","paragraphsAfterList":["Hiring our experienced attorneys increases your chances of receiving maximum compensation."]}]} /-->

<!-- wp:mbn-theme/section-location-cta-card-badges {"ctaTitle":"Contact Hastings & Hastings for a Personal Injury Lawyer in Buckeye, Arizona","ctaDescription":"If you or a loved one has been injured due to someone else’s negligence, do not wait to seek legal assistance. Contact Hastings & Hastings today for a free, no-obligation consultation. Our experienced personal injury attorneys are ready to fight for your rights and help you secure the compensation you deserve.","ctaButtonText":"Request Free Consultation","ctaPhoneText":"(480) 480-2929","ctaPhoneUrl":"tel:4804802929","ctaBackgroundImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-cta-card-bg-scaled.jpg","ctaBackgroundImageId":10723,"ctaLogoImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-logo-hh.svg","ctaLogoImageId":442,"badgesTextParagraphs":[{"id":1,"text":"We guarantee that you will speak with a licensed Arizona attorney at your initial consultation."},{"id":"mqtixigt6whkhhw9uev","text":"If we’re able to take your case, we’ll pursue compensation on your behalf in the maximum amount possible, and our experience and client testimonials make that clear. Our Discount Fee arrangement demonstrates our clear commitment to putting our clients first. Let us help you or your loved one with a personal injury case."}],"badgesItems":[{"id":1,"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-90-plus-combined-legal-experience-blck.svg","imageId":10028,"imageFallback":"","imageAlt":"Legal badge","imageWidth":303,"imageHeight":303},{"id":"mqtiza4y8787ula3bcj","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-29-percent-diiscount.svg","imageId":9916,"imageFallback":"","imageAlt":"","imageWidth":214,"imageHeight":214}]} /-->

<!-- wp:block {"ref":10731} /-->

<!-- wp:mbn-theme/section-video-bg-form {"videoMp4Url":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.mp4","videoWebmUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.webm","gravityFormId":"4","align":"full"} /-->
EOD
	,
);
