<?php
/**
 * Page Pattern: Casa Grande
 *
 * This file contains the complete page data for the 'Casa Grande' page.
 * It can be imported to create/update the page on other environments.
 *
 * Includes: Content, Featured Image, Status, Attributes, Custom Fields
 *
 * To use: Tools → Page Content Sync → Import All Pages from Files
 *
 * @package CustomTheme
 */

return array(
	'title'               => 'Casa Grande',
	'slug'                => 'casa-grande-personal-injury-attorney',
	'status'              => 'publish',
	'excerpt'             => '',
	'parent_slug'         => '',
	'menu_order'          => 0,
	'template'            => '',
	'featured_image_url'  => '',
	'featured_image_path' => '', // Theme assets path (ships via Git)
	'custom_fields'       => array(),
	'content'             => <<<'EOD'
<!-- wp:mbn-theme/hero-section {"eyebrowText":"Locations","mainHeading":"Casa Grande Personal Injury Lawyer","subheading":"Hastings & Hastings PC serves personal injury victims in Central Phoenix, Casa Grande, and surrounding Arizona communities. Since 1979, our experienced accident injury attorneys have helped clients pursue the compensation they deserve while they focus on healing and recovery.","badgeImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-90-plus-combined-legal-experience.svg","badgeImageId":9897,"videoMp4Url":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.mp4","videoMp4Id":417,"videoWebmUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.webm","videoWebmId":416,"overlayImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-fg-video-overlay-1.webp","overlayImageId":9912,"showCtaBar":false,"contentJustify":"justify-between","contentVerticalAlign":"items-end","textMaxWidth":"max-w-3xl"} /-->

<!-- wp:mbn-theme/section-location-intro {"title":"Why Choose Hastings &amp; Hastings As Your Casa Grande Personal Injury Attorney","introParagraph":"When you call to schedule a free consultation, you will meet with a licensed personal injury attorney, not a paralegal or salesperson. Our team provides one-on-one attention, proper case evaluation, and a strong negotiation approach that insurance companies have come to respect.&lt;br/>&lt;br/>Hastings &amp; Hastings is known as Arizona’s Discount Accident Injury Law Firm. Our personal injury cases are handled on a contingency fee basis, which means there are no upfront attorney fees. We also do not charge one-third of your settlement. Our discount fee is designed to put more money back in your pocket so you can focus on getting well again.","sections":[{"type":"attorneys","columnPosition":"text-left","subtitle":"Highly-Rated, Trusted Attorneys","paragraph":"Our team of experienced personal injury lawyers has more than 90 years of combined legal experience. Hiring our team of accident injury lawyers in Central Phoenix and Casa Grande, AZ is one of the most important decisions you can make.","teamImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-location-hastings-attorneys.jpg","teamImageId":10769},{"type":"fee-structure","columnPosition":"badge-left","badgeImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-29-percent-diiscount.svg","badgeImageId":9916,"subtitle":"Quality Legal Services at a Discount Price","paragraph":"Since 1979, we have been handling personal injury and accident cases. Insurance companies have come to respect our strong negotiation style. Our innovative approach to legal fees for accident victims means that all of our personal injury cases are handled on a contingency fee basis. We do not charge 1/3 of your settlement. Our discount fee puts more money in your pocket so that you can get back to what’s important after an accident – getting well again.”"},{"type":"attorneys","columnPosition":"text-left","subtitle":"Local Offices Throughout Phoenix","paragraph":"Our 12 offices across the Valley mean that we are close to you. We will work on your behalf so you can focus on the healing process and let us focus on your personal injury case.","teamImageUrl":"","teamImageId":0}],"subheaderTitle":"","ctaBackgroundImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-bg-cta-column-scaled.jpg","ctaBackgroundImageId":10765,"ctaLogoUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-logo-hh.svg","ctaLogoId":442,"ctaDescription":"You will be meeting with a licensed personal injury attorney—not a paralegal or salesperson."} /-->

<!-- wp:mbn-theme/section-location-office-location {"officeLocations":[{"name":"Casa Grande","address":"251 E. Cottonwood Lane, Ste. 251D Casa Grande, AZ 85122","addressUrl":"https://goo.gl/maps/gtBtdMnT2E6Dfqea6","phoneNumber":"(520) 421-9100","phoneUrl":"tel:5204219100","byAppointmentOnly":false}]} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"heading":"Comprehensive Accident Injury Legal Services","introParagraphs":["Our accident attorneys represent victims suffering from many types of auto accident injuries, including neck pain, back pain, and more serious injuries. We help clients understand their options, evaluate their case, and pursue the compensation available under Arizona law."],"listStyle":"two-column","listItems":[{"title":"Economic Damages","description":"To cover quantifiable losses such as medical expenses, lost wages, and property damage.","label":"Serious catastrophic injuries","url":"#"},{"title":"Non-economic Damages","description":"To compensate for subjective, non-monetary losses like pain, suffering, and emotional distress.","label":"Wrongful death","url":"#"},{"title":"Punitive Damages","description":"In some cases, a court may award you punitive damages if the at-fault party's conduct was particularly egregious, serving as a punishment and deterrent for such behavior.","label":"Semi-truck accidents","url":"#"},{"title":"","description":"","label":"Motorcycle accidents","url":"#"},{"title":"","description":"","label":"Bicycle accidents","url":"#"},{"title":"","description":"","label":"Dog bites","url":"#"},{"title":"","description":"","label":"Slip and falls","url":"#"},{"title":"","description":"","label":"Pedestrian accidents","url":"#"}],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-location-comprehensive-accident.jpg","imageId":10784,"beforeListParagraphs":["In addition to auto accident injury claims, Hastings &amp; Hastings also represents clients in cases involving:"],"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-cta-card-badges {"ctaTitle":"Years of Legal Experience in AZ","ctaDescription":"Our team of experienced personal injury lawyers has more than 90 years of combined legal experience. Hiring our team of <a href="/practice-areas/auto-accident-injuries/">accident injury lawyers in Chandler, Gilbert and Ahwatukee</a> is one of the most important decisions you can make.","ctaButtonText":"Request Free Consultation","ctaBackgroundImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-cta-card-bg-scaled.jpg","ctaBackgroundImageId":10723,"ctaLogoImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-logo-hh.svg","ctaLogoImageId":442,"badgesTextParagraphs":[{"id":1,"text":"We guarantee that you will speak with a licensed Arizona attorney at your initial consultation."},{"id":"mquti797cixxnghjf6r","text":"If we’re able to take your case, we’ll pursue compensation on your behalf in the maximum amount possible, and our experience and client testimonials make that clear. Our Discount Fee arrangement demonstrates our clear commitment to putting our clients first. Let us help you or your loved one with a personal injury case."}],"badgesItems":[{"id":1,"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-90-plus-combined-legal-experience-blck.svg","imageId":10028,"imageFallback":"","imageAlt":"90+ Combined Legal Experience","imageWidth":303,"imageHeight":303},{"id":"mqutivzvrt9bhalydmf","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-29-percent-diiscount.svg","imageId":9916,"imageFallback":"","imageAlt":"29% Fee — Discount Accident Lawyers badge","imageWidth":214,"imageHeight":214}]} /-->

<!-- wp:block {"ref":10773} /-->

<!-- wp:mbn-theme/section-video-bg-form {"videoMp4Url":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.mp4","videoWebmUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.webm","gravityFormId":"4","align":"full"} /-->
EOD
	,
);
