<?php
/**
 * Page Pattern: Chandler
 *
 * This file contains the complete page data for the 'Chandler' page.
 * It can be imported to create/update the page on other environments.
 *
 * Includes: Content, Featured Image, Status, Attributes, Custom Fields
 *
 * To use: Tools → Page Content Sync → Import All Pages from Files
 *
 * @package CustomTheme
 */

return array(
	'title'               => 'Chandler',
	'slug'                => 'chandler-personal-injury-lawyer',
	'status'              => 'publish',
	'excerpt'             => '',
	'parent_slug'         => '',
	'menu_order'          => 0,
	'template'            => '',
	'featured_image_url'  => '',
	'featured_image_path' => '', // Theme assets path (ships via Git)
	'custom_fields'       => array(),
	'content'             => <<<'EOD'
<!-- wp:mbn-theme/hero-section {"eyebrowText":"Locations","mainHeading":"Chandler Personal Injury Lawyer","subheading":"Our Phoenix personal injury attorneys serve clients in the Chandler area with decades of experience, local resources, and a strong reputation for helping injury victims pursue fair compensation. We work on a contingency fee basis, which means you do not pay unless we recover compensation for you.","badgeImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-90-plus-combined-legal-experience.svg","badgeImageId":9897,"videoMp4Url":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.mp4","videoMp4Id":417,"videoWebmUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.webm","videoWebmId":416,"overlayImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-fg-video-overlay-1.webp","overlayImageId":9912,"showCtaBar":false,"contentJustify":"justify-between","textMaxWidth":"max-w-3xl"} /-->

<!-- wp:mbn-theme/section-location-intro {"title":"Why Choose Hastings &amp; Hastings As Your Chandler Personal Injury Attorney","introParagraph":"Our skilled injury and <a href=\"/chandler-car-accident-attorney/\">accident lawyers in Chandler</a> are highly rated and respected throughout the Chandler and Phoenix area. Our Chandler personal injury attorneys use strong negotiation skills and comprehensive service to diligently handle all aspects of personal injury cases, delivering a track record of success for our clients. Call our law firm today to talk about our discounted rate and contingency-based pay method. We offer free evaluations so we can quickly begin strategizing a plan for your unique case.","sections":[{"type":"attorneys","columnPosition":"text-left","subtitle":"Highly-Rated, Trusted Attorneys","paragraph":"Our team of experienced personal injury lawyers has more than 90 years of combined legal experience. Choosing our accident injury lawyers in Chandler and throughout Arizona can be one of the most important decisions you make.","teamImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-location-hastings-attorneys.jpg","teamImageId":10769},{"type":"attorneys","columnPosition":"image-left","subtitle":"Proven Track Record from Real Clients","paragraph":"Our legal team has recovered millions of dollars for injured parties through verdicts or settlements. We’ll handle all the legalities so you can focus on your recovery.","teamImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-local-offices-throughout-phoenix.jpg","teamImageId":10799}],"subheaderTitle":"","ctaBackgroundImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-bg-cta-column-scaled.jpg","ctaBackgroundImageId":10765,"ctaLogoUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-logo-hh.svg","ctaLogoId":442,"ctaDescription":"Contact Hastings &amp; Hastings today for a free evaluation of your case so we can begin building a plan for your recovery."} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"backgroundColor":"bg-light-blue-100","heading":"Comprehensive Accident Injury Legal Services","introParagraphs":["No one ever begins their day expecting an accident, yet each year, nearly 40 million personal injuries requiring medical treatment occur in the US. While car accidents are the most common cause of personal injuries, they aren’t the only way injuries occur.","Suffering a significant injury can be traumatic, but when the injury happens due to the negligence, recklessness, or wrongdoing of someone else it’s particularly distressing and may be a cause for a personal injury claim or lawsuit."],"listStyle":"two-column","listItems":[{"id":"mr1zleu9bnfw2pl6u7","title":"","description":"","label":"Car accidents","url":"/practice-areas/auto-accident-injuries/"},{"id":"mr1fy6ldtqkxa2de88t","title":"","description":"","label":"Truck accidents","url":"/truck-accident-lawyer/"},{"id":"mr1fycuh75piiuimzsw","title":"","description":"","label":"Motorcycle accidents","url":"/practice-areas/motorcycle-accidents/"},{"id":"mr1fysighgne82wefvc","title":"","description":"","label":"Pedestrian accidents","url":"/practice-areas/phoenix-pedestrian-accident-attorney/"},{"id":"mr1fyicx8aay9nm4map","title":"","description":"","label":"Bicycle Accidents","url":"/practice-areas/bicycle-accidents/"},{"id":"mr1fyuajn5lh0hwdlv","title":"","description":"","label":"Slip and fall","url":"/practice-areas/slip-falls/"},{"id":"mr1fyzvdqjd4kofdh2","title":"","description":"","label":"Workplace accidents","url":"/phoenix-workplace-injury-attorney/"},{"id":"mr1fz502cfo4q0v73be","title":"","description":"","label":"Dog bites and animal attacks","url":"/practice-areas/dog-bites/"}],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-location-comprehensive-accident-injury-legal-services.jpg","imageId":11230,"beforeListParagraphs":["The most common causes of personal injuries include:"],"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue-100","rows":[{"heading":"","paragraphs":["<a href=\"/chandler-catastrophic-injury-lawyer/\">Some injuries are catastrophic</a> and cause serious economic and non-economic damages to the injured person and their family. Even less serious injuries may require medical treatment, expensive medications, appointments, follow-ups, and lost time from the workplace. When the injury occurs due to someone else’s actions or inaction, even if you are <a href=\"/chandler-pedestrian-accident-attorney/\">looking for a Chandler pedestrian accident attorney</a>, that person is responsible for compensating you for your damages—the physical and financial consequences of the injury. Compensation typically comes through the at-fault party’s insurance policy."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-location-catastropic-injuries.jpg","imageId":11188,"imagePosition":"left","id":"mr1d7lv0o5x2rc6s83p"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue-100","rows":[{"heading":"","paragraphs":["Our Chandler injury attorneys know how to help. At Hastings &amp; Hastings, PC, in Chandler, we feel passionate about using our 40 years of experience in personal injury law to negotiate substantial settlements for our personal injury clients or to litigate for them in the courtroom. Call our Chandler Personal Injury law firm today for a free evaluation of your case."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-understanding-personal-injury-cases.jpg","imageId":10747,"imagePosition":"right","id":"mr1d7lv0o5x2rc6s83p"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"heading":"How Can Our Chandler Personal Injury Attorney Help?","introParagraphs":["Our Chandler personal injury attorney will represent your interests by using their investigative skills and resources to gather and review the evidence in your case, draft a demand letter to the appropriate insurance company, and strongly negotiate for the best possible settlement. Your attorney will use the following evidence and investigative methods to support your case:","Our legal team’s 9 decades of combined experience in personal injury law in Scottsdale and the Phoenix area means we have the knowledge and resources to investigate your case, hear witness testimony, and hire accident reconstruction specialists if needed to prove liability."],"listItems":[{"title":"","description":"Examine the police report, accident report, or incident report","label":"","url":"","id":"mr1cw9gv82nx7hnd8ha"},{"title":"","description":"Examine medical records and bills related to the injury","label":"","url":"","id":"mr1cw9gvrlpsshanv4"},{"title":"","description":"View any photo evidence or surveillance video  ","label":"","url":"","id":"mr1cw9gvq5rpoafznv"},{"id":"mr1cxgkz9sxc6700dkm","title":"","description":"Interview eyewitnesses to the event","label":"","url":""},{"id":"mr20txwxyd2m75ykaw","title":"","description":"Gather testimony from expert witnesses such as accident reconstruction specialists and medical experts","label":"","url":""},{"id":"mr20u7vwnjvm7gfdlq","title":"","description":"Interview close family and friends for evidence of the injury’s impact on your life","label":"","url":""}],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-location-liability-personal-injury.jpg","imageId":11190,"beforeListParagraphs":["In order to show liability in Arizona personal injury cases, the plaintiff must prove the following:"],"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue","rows":[{"heading":"","paragraphs":["Our diligent <a href=\"/queen-creek-personal-injury-attorney/\">team of personal injury attorneys</a> provides individualized attention to our clients. We will keep in close contact throughout the process, informing you every step of the way as we work to maximize your chances of full compensation for the damages you’ve suffered. We have specialized areas of expertise such <a href=\"/chandler-motorcycle-accident-lawyer/\">as our Chandler Motorcycle Accident Lawyer</a>."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-how-hastings-n-hastings-can-help.jpg","imageId":10741,"imagePosition":"left","id":"mr1d7lv0o5x2rc6s83p"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"backgroundColor":"bg-light-blue-100","heading":"Understanding Liability in Chandler Personal Injury Cases","introParagraphs":["When someone’s been harmed through negligence or wrongful actions on the part of another, the state demands that the victim prove liability. Taking on the complexities of the Arizona legal system while you’re busy dealing with physical trauma and the chaotic aftermath of an accident is daunting. A Chandler Arizona personal injury lawyer can investigate all aspects of your case in order to prove the other party’s liability. Showing liability in personal injury cases requires proving the following:"],"listItems":[{"title":"","description":"That the person or entity at fault had a duty of care to keep you and others safe through reasonable actions; for example, by driving carefully and following traffic rules or by keeping a store or hotel free from potential dangers","label":"","url":"","id":"mr1cw9gv82nx7hnd8ha"},{"title":"","description":"That the liable party breached their duty of care through an act of negligence, reckless behavior, or wrongdoing","label":"","url":"","id":"mr1cw9gvrlpsshanv4"},{"title":"","description":"That the breach of this duty of care directly caused the injury","label":"","url":"","id":"mr1cw9gvq5rpoafznv"},{"id":"mr1cxgkz9sxc6700dkm","title":"","description":"That the injured person suffered economic losses and non-economic losses, directly due to the injury","label":"","url":""}],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-liocation-injury-legal-service.jpg","imageId":11217,"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue-100","rows":[{"heading":"","paragraphs":["<a href=\"/\">At our Chandler Law Firm,</a> we use our strong local reputation, experience, and investigative skills to collect evidence to prove all of the above. We will advocate on your behalf with compelling evidence throughout negotiations with the at-fault person’s insurance party, while you focus your energy on healing from your injuries. If necessary, we will not shy away from fighting on your behalf in court."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-statute-of-limitation.jpg","imageId":10736,"imagePosition":"left","id":"mr1d7lv0o5x2rc6s83p"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"heading":"What Compensation Can You Get for Your Damages in an Arizona Personal Injury Case?","introParagraphs":["While it’s true that financial compensation doesn’t undo an injury, it can support access to the best medical care and minimize financial concerns throughout the recovery process. In many cases, it also helps the injured person and their family achieve a sense of justice.","Civil law in Arizona recognizes two types of damages: economic and non-economic. In many cases, non-economic damages can be even more harmful than the economic ones associated with an accident. Examples of both types of damages include the following:"],"listItems":[{"title":"","description":"Medical expenses and future expenses related to medical care","label":"","url":"","id":"mr1cw9gv82nx7hnd8ha"},{"title":"","description":"Lost earnings from missed work and estimated future lost earnings for ongoing treatment or procedures","label":"","url":"","id":"mr1cw9gvrlpsshanv4"},{"title":"","description":"Reduced potential for future earnings in the case of a disabling accident","label":"","url":"","id":"mr1cw9gvq5rpoafznv"},{"id":"mr1cxgkz9sxc6700dkm","title":"","description":"Pain and suffering","label":"","url":""},{"id":"mr222k9vnm2sv66h9r","title":"","description":"Emotional anguish and loss of enjoyment of life","label":"","url":""},{"id":"mr222qp36v1q7ou3u87","title":"","description":"Scarring or disfigurement","label":"","url":""}],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-liocation-injury-legal-service.jpg","imageId":11217,"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue","rows":[{"heading":"","paragraphs":["Victims of personal injuries that result from another party’s actions deserve compensation for any or all of the above damages. Some personal injury claims can even become wrongful death claims when an injury leads to death."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-location-victims-of-personal-injury.jpg","imageId":11229,"imagePosition":"left","id":"mr1d7lv0o5x2rc6s83p"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue-100","rows":[{"heading":"Do You Have to Go to Court for a Personal Injury Claim in Arizona?","paragraphs":["The vast majority of personal injury cases settle outside of court. The attorneys at Hastings &amp; Hastings investigate the evidence in personal injury cases and use our over 90 years of combined legal experience to craft a compelling case. We will do everything we can to win a substantial settlement from an insurance company for you. If necessary, we are more than willing to go to court to litigate your case to gain the jury verdict you need for a court award for damages. We strongly believe in your right to full compensation for the losses a personal injury can inflict on your life."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-location-go-to-court-personal-injury.jpg","imageId":11231,"imagePosition":"right","id":"mr1eil79qhm345ui5cd"}]} /-->

<!-- wp:mbn-theme/section-location-cta-card-badges {"ctaTitle":"Years of Legal Experience in AZ","ctaDescription":"Our team of experienced personal injury lawyers has more than 90 years of combined legal experience. Hiring our team of <a href=\"/practice-areas/auto-accident-injuries/\">accident injury lawyers in Chandler, Gilbert and Ahwatukee</a> is one of the most important decisions you can make.","ctaButtonText":"Request Free Consultation","ctaBackgroundImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-cta-card-bg-scaled.jpg","ctaBackgroundImageId":10723,"ctaLogoImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-logo-hh.svg","ctaLogoImageId":442,"badgesTextParagraphs":[{"id":1,"text":"We guarantee that you will speak with a licensed Arizona attorney at your initial consultation."},{"id":"mr1c4lkebfnzal5ldnd","text":"If we’re able to take your case, we’ll pursue compensation on your behalf in the maximum amount possible, and our experience and client testimonials make that clear. Our Discount Fee arrangement demonstrates our clear commitment to putting our clients first. Let us help you or your loved one with a personal injury case."}],"badgesItems":[{"id":1,"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-90-plus-combined-legal-experience-blck.svg","imageId":10028,"imageFallback":"","imageAlt":"90+ Combined Legal Experience","imageWidth":303,"imageHeight":303},{"id":"mr1c4zebrktube3ghp","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-29-percent-diiscount.svg","imageId":9916,"imageFallback":"","imageAlt":"29% Fee — Discount Accident Lawyers badge","imageWidth":214,"imageHeight":214}]} /-->

<!-- wp:block {"ref":10773} /-->

<!-- wp:mbn-theme/section-video-bg-form {"videoMp4Url":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.mp4","videoWebmUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.webm","gravityFormId":"4","align":"full"} /-->
EOD
	,
);
