<?php
/**
 * Page Pattern: Gilbert
 *
 * This file contains the complete page data for the 'Gilbert' page.
 * It can be imported to create/update the page on other environments.
 *
 * Includes: Content, Featured Image, Status, Attributes, Custom Fields
 *
 * To use: Tools → Page Content Sync → Import All Pages from Files
 *
 * @package CustomTheme
 */

return array(
	'title'               => 'Gilbert',
	'slug'                => 'gilbert-personal-injury-lawyer',
	'status'              => 'publish',
	'excerpt'             => '',
	'parent_slug'         => '',
	'menu_order'          => 0,
	'template'            => 'page-templates/template-blank.php',
	'featured_image_url'  => '',
	'featured_image_path' => '', // Theme assets path (ships via Git)
	'custom_fields' 	  => "{'_wp_page_template':'page-templates/template-blank.php','translate_parts':'0'}",
	'content'             => <<<'EOD'
<!-- wp:mbn-theme/hero-section {"eyebrowText":"Locations","mainHeading":"Gilbert Creek Personal Injury Lawyer","subheading":"If you or a family member has been injured through the fault of someone else, the Phoenix personal injury attorneys at Hastings & Hastings PC of Gilbert are here to advocate for the best possible compensation for you.  Our team has successfully helped many clients include motorcycle drivers that were injured from other drivers. Call our Gilbert office today to schedule a free case evaluation.","badgeImageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-90-plus-combined-legal-experience.svg","badgeImageId":9897,"videoMp4Url":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.mp4","videoMp4Id":417,"videoWebmUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.webm","videoWebmId":416,"overlayImageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-fg-video-overlay.webp","overlayImageId":8556,"showCtaBar":false,"contentJustify":"justify-between","textMaxWidth":"max-w-3xl"} /-->

<!-- wp:mbn-theme/section-location-intro {"title":"Why Choose Hastings &amp; Hastings As Your Gilbert Creek Personal Injury Attorney","introParagraph":"If you’ve experienced an injury and it was caused by someone else’s negligence, we can help you get the compensation you’re entitled to. Here’s why you should work with us:","sections":[{"type":"attorneys","columnPosition":"text-left","subtitle":"Highly-Rated, Trusted Attorneys","paragraph":"Our team of experienced personal injury lawyers has more than 90 years of combined legal experience. Choosing our accident injury lawyers in Glendale and throughout Arizona can be one of the most important decisions you make.","teamImageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-location-hastings-attorneys.jpg","teamImageId":10131},{"type":"fee-structure","columnPosition":"badge-left","badgeImageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/07/badge-nofee.svg","badgeImageId":10932,"subtitle":"When you contact us and schedule a consultation, it is always free and with a licensed attorney who can provide guidance regarding your claim.","paragraph":"When you contact us and schedule a consultation, it is always free and with a licensed attorney who can provide guidance regarding your claim."},{"type":"attorneys","columnPosition":"text-left","subtitle":"Local Offices Throughout Phoenix","paragraph":"Not only do our Gilbert personal injury lawyers enjoy a strong local reputation and valuable resources for proving your case, but we have 10 offices in the Phoenix area and the surrounding region so you can find an office close to you.","teamImageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-local-offices-throughout-phoenix.jpg","teamImageId":10151}],"subheaderTitle":"","ctaBackgroundImageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-bg-cta-column-scaled.jpg","ctaBackgroundImageId":10132,"ctaLogoUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-logo-hh.svg","ctaLogoId":310,"ctaDescription":"It’s our passion to present your case in the strongest possible terms to insurance companies and in court so you secure compensation for your damages. Call us today for a free evaluation of your personal injury case."} /-->

<!-- wp:mbn-theme/section-location-office-location {"officeLocations":[{"name":"Central Phoenix Office","address":"1221 E. Osborn Rd. Suite A202 Phoenix 85014","addressUrl":"https://www.google.com/maps?cid=17756511556322746656","phoneNumber":"(602) 433-2323","phoneUrl":"tel:6024332323","byAppointmentOnly":false}]} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"backgroundColor":"bg-light-blue-100","heading":"Comprehensive Accident Injury Legal Services","introParagraphs":["Unfortunately, accidents causing personal injuries happen to a significant number of people every day. Arizona residents experienced over 120,000 car crashes on state roadways in 2021, but car accidents are not the only way people can sustain a personal injury. While car crashes are the most common cause of serious injuries, some other causes of personal injuries include the following:"],"listStyle":"two-column","listItems":[{"id":"mr1fycuh75piiuimzsw","title":"","description":"","label":"","url":"/practice-areas/motorcycle-accidents/"},{"id":"mr1fy6ldtqkxa2de88t","title":"","description":"","label":"Truck accidents","url":"/truck-accident-lawyer/"},{"id":"mr1fysighgne82wefvc","title":"","description":"","label":"Pedestrian accidents","url":"/practice-areas/phoenix-pedestrian-accident-attorney/"},{"id":"mr1fyicx8aay9nm4map","title":"","description":"","label":"Bicycle Accidents","url":"/practice-areas/bicycle-accidents/"},{"id":"mr1fyuajn5lh0hwdlv","title":"","description":"","label":"Slip and fall","url":"/practice-areas/slip-falls/"},{"id":"mr1zleu9bnfw2pl6u7","title":"","description":"","label":"Slip and fall incidents","url":"/practice-areas/slip-falls/ "},{"id":"mr1fyzvdqjd4kofdh2","title":"","description":"","label":"Accidents in the workplace","url":"/phoenix-workplace-injury-attorney/"},{"id":"mr1fz502cfo4q0v73be","title":"","description":"","label":"Dog bites and animal attacks","url":"/practice-areas/dog-bites/"}],"imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/07/gilbert-img-1.jpg","imageId":10939,"beforeListParagraphs":["The most common causes of personal injuries include:"],"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue-100","rows":[{"heading":"","paragraphs":["Some accidents lead to catastrophic <a href="/gilbert-catastrophic-injury-attorney/" data-type="link" data-id="/gilbert-wrongful-death-attorney/">injuries with life-altering impacts</a> or <a href="/gilbert-wrongful-death-attorney/" data-type="link" data-id="/gilbert-wrongful-death-attorney/">can even lead to death</a>. Other injuries are less severe but still cause economic and non-economic losses throughout the recovery process. When an injury occurred due to someone else’s negligence it can be even more distressing for victims."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/07/gilbert-img-2.jpg","imageId":10940,"imagePosition":"left","id":"mr23sezq570utsy8njt"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue-100","rows":[{"heading":"","paragraphs":["When the dust settles after an accident, it helps to understand how <a href="/gilbert-car-accident-lawyer/" data-type="link" data-id="/gilbert-car-accident-lawyer/">important our Gilbert Car Accident Lawyer and</a> personal injury claim can be as part of your overall recovery."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/07/gilbert-img-3.jpg","imageId":10941,"imagePosition":"right","id":"mr1d7lv0o5x2rc6s83p"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"heading":"Understanding Liability in an Arizona Personal Injury Lawsuit","introParagraphs":["Personal injury claims in Gilbert and the Phoenix area require injury victims to prove who was liable for their injury even if you were a pedestrian at the time of the accident. The Arizona system for civil cases can be challenging to navigate effectively. A diligent lawyer with decades of experience in the state’s personal injury system understands exactly how to investigate claims to highlight the fault of the liable person or entity. Our team of skilled attorneys will focus their 9 decades of combined experience on investigating liability in your case through:"],"listItems":[{"title":"","description":"Scrutinizing the accident report, incident report, or police report related to your injury","label":"","url":"","id":"mr1cw9gv82nx7hnd8ha"},{"title":"","description":"Examine medical records and bills related to the injury","label":"","url":"","id":"mr1cw9gvrlpsshanv4"},{"title":"","description":"Requesting traffic cam footage, surveillance video, or dash cam video of your injury when available","label":"","url":"","id":"mr1cw9gvq5rpoafznv"},{"id":"mr1cxgkz9sxc6700dkm","title":"","description":"Interviewing eyewitnesses","label":"","url":""},{"id":"mr20txwxyd2m75ykaw","title":"","description":"Hiring accident reconstruction experts and medical experts when required","label":"","url":""},{"id":"mr20u7vwnjvm7gfdlq","title":"","description":"Reviewing your medical records to show damages related to the accident","label":"","url":""}],"imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/07/gilbert-img-4.jpg","imageId":10942,"beforeListParagraphs":["In order to show liability in Arizona personal injury cases, the plaintiff must prove the following:"],"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue","rows":[{"heading":"Arizona requires that personal injury victims prove liability by showing the following:","paragraphs":[],"listStyle":"single","listItems":[{"id":"mr4vcqblbpd1atwo1ul","title":"","description":"That the defendant owed a duty of care toward you and others through reasonable actions such as a hotel owner’s responsibility to keep their premises safe from hazards or a driver’s duty to avoid dangerous distractions such as texting and driving","label":"","url":""},{"id":"mr4vczi0j0o26ywtlq","title":"","description":"That the defendant breached that duty of care through an act of negligence, recklessness, or wrongdoing","label":"","url":""},{"id":"mr4vd7hkr9jc8oqwlb","title":"","description":"That their negligent breach directly caused your injury","label":"","url":""},{"id":"mr4vd9m5zraj7vgy5j","title":"","description":"That you’ve suffered damages due to the injury","label":"","url":""}],"paragraphsAfterList":[],"imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/07/gilbert-img-5.jpg","imageId":10943,"imagePosition":"left","id":"mr23sezv6ctu1uf5fvb"},{"id":"mr4vpnvnbf58v8ucenv","heading":"","paragraphs":["The team of Hastings &amp; Hastings has a long track record of success in our investigations. We work hard to clearly prove the liability of responsible parties so our clients receive the maximum possible compensation."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"","imageId":0,"imagePosition":"right"}],"className":"pt-40 text-center"} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"backgroundColor":"bg-light-blue-100","heading":"What Compensation Can You Get After a Personal Injury in Arizona?","introParagraphs":["Arizona’s court systems understand that monetary compensation not only relieves financial burdens but also addresses the non-economic suffering that victims of all accident types experience. Compensation for damages helps an injured person achieve a sense of justice when someone else caused their injury. In an Arizona personal injury case, you’re likely to gain compensation for the following damages:"],"listItems":[{"title":"","description":"Your medical expenses and any upcoming or future expenses for necessary treatments","label":"","url":"","id":"mr1cw9gv82nx7hnd8ha"},{"title":"","description":"Any lost wages from missed work days and potential future lost wages","label":"","url":"","id":"mr1cw9gvrlpsshanv4"},{"title":"","description":"Diminished earning capacity in the case of a disabling accident","label":"","url":"","id":"mr1cw9gvq5rpoafznv"},{"id":"mr1cxgkz9sxc6700dkm","title":"","description":"Pain and suffering","label":"","url":""},{"id":"mr4vjlmyyk4er2oqkg","title":"","description":"Emotional anguish, PTSD, Depression, or anxiety","label":"","url":""},{"id":"mr4vju7pr7v61f2qvnb","title":"","description":"Scarring or disfigurement","label":"","url":""},{"id":"mr4vk0znolzoe0mq9tk","title":"","description":"Loss of consortium (when you’ve lost the ability to enjoy many aspects of a full relationship with a spouse or romantic partner or are no longer able to fully support and be active with your children)","label":"","url":""},{"id":"mr4vk79aba8l1cy5c9b","title":"","description":"Lost quality of life","label":"","url":""}],"imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/07/gilbert-img-6.jpg","imageId":10944,"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue-100","rows":[{"heading":"","paragraphs":["These are examples of both economic and non-economic damages. Injury victims deserve compensation for both types of damages to their physical and financial health. In the worst-case scenario, some injuries may lead to death, causing a personal injury claim to become a wrongful death claim made by a close family member."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/07/gilbert-img-7.jpg","imageId":10945,"imagePosition":"left","id":"mr23sezzh5xtdee2c6c"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue","rows":[{"heading":"Will You Have to Go to Court for Your Personal Injury Case?","paragraphs":["The law firm of Hastings &amp; Hastings PC offers free evaluations of personal injury cases in Gilbert. Once we form a strategy for your compensation we will keep you informed of every step and all progress made on your claim. In most cases, our firm’s strong local reputation and powerful negotiation skills are enough to encourage insurance companies to negotiate a settlement for our clients so they never have to see a courtroom. We will investigate your case, take steps to show liability, and draft a demand letter to the liable party’s insurance company. If required, we also stand ready to argue aggressively on your behalf in court to work toward a positive outcome for compensation for all of your damages.<br>You deserve to recover your financial losses so you can focus on your physical recovery and take important steps toward moving forward."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/07/gilbert-img-8.jpg","imageId":10946,"imagePosition":"right","id":"mr1d7lv0o5x2rc6s83p"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"heading":"Common Tactics Insurance Companies Use to Deny Claims","introParagraphs":["No matter how compassionate an insurance adjuster sounds on the phone, keep in mind that their company’s business model depends on taking in a lot of money in premiums and paying out as little in claims as they can. A good lawyer understands the tactics many insurance companies use and their reasons. Some common tactics an insurance company might use to deny a claim outright or try to lowball it during negotiations include the following:"],"listItems":[{"id":"mr4w6p8rywfmnaw4vzr","title":"","description":"Calling you with an undervalued offer very soon after your accident when you can’t yet know the extent of the damages","label":"","url":""},{"id":"mr4w6zmigwfrdwuag4r","title":"","description":"Recording phone calls and then using your words out of context later","label":"","url":""},{"id":"mr4w7km53heagxmqwwb","title":"","description":"Denying their client’s liability or stating that coverage wasn’t in place at the time the accident occurred","label":"","url":""},{"id":"mr4w7o46xtoi0x8wtei","title":"","description":"Disputing some of your medical bills by claiming your treatment was unnecessary","label":"","url":""},{"id":"mr4w7sd3eg1kh6kbkme","title":"","description":"Using delaying tactics so you settle for a low amount or give up entirely","label":"","url":""},{"id":"mr4w8idyxytfq9rxnnc","title":"","description":"Encouraging you to avoid hiring an attorney","label":"","url":""}],"imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/07/gilbert-img-9.jpg","imageId":10947,"afterListParagraphs":[""],"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue-100","rows":[{"id":"mr4w8s23nnzmoowij7","heading":"","paragraphs":["It’s best to hire an attorney after your accident as soon as you understand the scope of your injury and the physical and financial damages related to it. Direct all calls from insurance companies to your attorney."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/07/gilbert-img-10.jpg","imageId":10948,"imagePosition":"left"}]} /-->

<!-- wp:mbn-theme/section-location-cta-card-badges {"ctaTitle":"Need a Personal Injury Lawyer in Peoria, AZ?","ctaDescription":"If you’ve been injured due to someone else’s negligence, it’s important to take action and protect your rights. Contact Hastings & Hastings today to schedule a free consultation with one of our experienced personal injury and car accident lawyers in Queen Creek. We are here to listen to your story and evaluate your case to help you get the justice and compensation you deserve.","ctaButtonText":"Request Free Consultation","ctaBackgroundImageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-cta-card-bg-scaled.jpg","ctaBackgroundImageId":10135,"ctaLogoImageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-logo-hh.svg","ctaLogoImageId":310,"badgesTextParagraphs":[{"id":1,"text":"We guarantee that you will speak with a licensed Arizona attorney at your initial consultation."},{"id":"mr252tu7dme1n6aodhe","text":"If we’re able to take your case, we’ll pursue compensation on your behalf in the maximum amount possible, and our experience and client testimonials make that clear. Our Discount Fee arrangement demonstrates our clear commitment to putting our clients first. Let us help you or your loved one with a personal injury case."}],"badgesItems":[{"id":1,"imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-90-plus-combined-legal-experience-blck.svg","imageId":8651,"imageFallback":"","imageAlt":"90+ Years Combined Legal Experience","imageWidth":303,"imageHeight":303},{"id":"mr253fdflnzgm1yibrc","imageUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-29-percent-diiscount.svg","imageId":8559,"imageFallback":"","imageAlt":"29% Fee — Discount Accident Lawyers badge","imageWidth":214,"imageHeight":214}]} /-->

<!-- wp:block {"ref":10144} /-->

<!-- wp:mbn-theme/section-video-bg-form {"videoMp4Url":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.mp4","videoWebmUrl":"https://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.webm","gravityFormId":"4","align":"full"} /-->
EOD
	,
);
