<?php
/**
 * Page Pattern: Homepage
 *
 * This file contains the complete page data for the 'Homepage' page.
 * It can be imported to create/update the page on other environments.
 *
 * Includes: Content, Featured Image, Status, Attributes, Custom Fields
 *
 * To use: Tools → Page Content Sync → Import All Pages from Files
 *
 * @package CustomTheme
 */

return array(
	'title'               => 'Homepage',
	'slug'                => 'sample-page',
	'status'              => 'publish',
	'excerpt'             => '',
	'parent_slug'         => '',
	'menu_order'          => 0,
	'template'            => 'page-templates\/template-sample.php',
	'featured_image_url'  => '',
	'featured_image_path' => '', // Theme assets path (ships via Git)
	'custom_fields'       => array( '_wp_page_template' => 'page-templates\/template-sample.php' ),
	'content'             => <<<'EOD'
<!-- wp:mbn-theme/hero-section {"badgeImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/05/badge-29-percent-fee.svg","badgeImageId":56,"videoMp4Url":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-hero-homepage-opt.mp4","videoMp4Id":389,"videoWebmUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-hero-homepage-opt.webm","videoWebmId":390,"posterImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-hero.jpg","posterImageId":392,"overlayImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-hero-overlay.png","overlayImageId":394} /-->

<!-- wp:mbn-theme/section-intro-homepage {"backgroundImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-intro-bg-homepage.jpg","backgroundImageId":399,"awards":[{"id":"mpxasj0jom49168du4","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/awards_state-bar-of-az.svg","imageId":400},{"id":"mpxat02w3y86l2a1ogk","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/awards_american-association-for-justice.svg","imageId":401},{"id":"mpxat86qq7z70ibicxk","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/awards_expertise-best-personal-injury-lawyers-in-phx-2022.svg","imageId":403},{"id":"mpxate7p88a58psnq5c","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/awards_elite-lawyer.svg","imageId":402}]} /-->

<!-- wp:mbn-theme/section-testimonial-badges {"testimonials":[{"id":"mpxs72khlcsuond393j","starRating":5,"content":"..their office handle pretty much everything... I could focus on getting my life back to normal. It was great to not have to worry about anything...","author":"Verified Client"},{"id":"mpxs7qxd6iw0egigh9v","starRating":5,"content":"The team was incredibly professional and guided me through every step. Their expertise made a difficult situation much easier to handle. I'm grateful for their support.","author":"Verified Client"},{"id":"mpxs84k0whdxeyey47q","starRating":5,"content":"From our first consultation to the final settlement, communication was clear and consistent. They truly cared about my case and fought hard for the best outcome possible.","author":"Verified Client"}],"badges":[{"id":"mpxsbt1l16rfreofube","iconUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/workspace_premium.svg","iconId":410,"primaryText":"Serving Arizona","secondaryText":"Since 1979"},{"id":"mpxsczbwjs52nccay4c","iconUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/verified.svg","iconId":412,"primaryText":"One of Arizona’s Long-Standing","secondaryText":"Personal Injury Firms"},{"id":"mpxsdef8m34vugh2hhj","iconUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/location_on.svg","iconId":411,"primaryText":"Serving Clients Across","secondaryText":"10 Valley Locations"}]} /-->

<!-- wp:mbn-theme/section-3col-badge-cta {"videoMp4Url":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.mp4","videoMp4Id":417,"videoWebmUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.webm","videoWebmId":416,"posterImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-more-affordable-poster.jpg","posterImageId":419,"badges":[{"id":"mpxyxjfyfmycjduvwi4","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-no-fee-until-we-win.svg","imageId":423,"text":"You pay nothing upfront and nothing out of pocket. Hastings & Hastings only gets paid if your case results in a recovery."},{"id":"mpxz039sq9646y8hid","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/05/badge-29-percent-fee.svg","imageId":56,"text":"Hastings & Hastings is known for its 29% settlement fee, giving clients a more affordable way to get experienced legal representation."},{"id":"mpxz0dgg1w6agsqd1y9","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-lower-fees.svg","imageId":422,"text":"Compared to firms that charge 33%, our lower fee structure gives Hastings & Hastings a meaningful cost advantage."}]} /-->

<!-- wp:mbn-theme/section-case-results {"mainHeading":"<span class="text-secondary">Proven experience.</span> <span class="inline-block">Real results.</span>","caseResults":[{"id":"mpz78lx5iom4ly53q1r","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/Placeholder-Image-2.jpg","imageId":428,"tagText":"Car Accident","caseHeading":"$15,000,000","caseSubheading":"Catastrophic automobile accident result involving serious injuries.","caseContent":"Our lower fee structure helped this client keep an additional $1,050,000 compared to a typical 45% litigation fee."},{"id":"mpz7bvvvv620oz34hcs","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/Placeholder-Image-1.jpg","imageId":427,"tagText":"Motorcycle Accident","caseHeading":"$300,000","caseSubheading":"Motorcycle accident result.","caseContent":"Our lower fee structure helped this client keep an additional $10,000."},{"id":"mpz7cr5i1dalhmbfbdy","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/Placeholder-Image.jpg","imageId":426,"tagText":"Wrongful Death","caseHeading":"$1,687,682","caseSubheading":"Wrongful death settlement result.","caseContent":"Our lower fee structure helped this client keep an additional $73,133."}]} /-->

<!-- wp:mbn-theme/section-practice-areas {"cards":[{"id":"mpzbvqjydojg7661i","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/placeholder-car-accidents.jpg","imageId":431,"heading":"Car Accidents","description":"Help for drivers and passengers injured because of someone else’s negligence."},{"id":"mpzbwl4t908qbxftxk7","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/placeholder-truck-accidents.jpg","imageId":435,"heading":"Truck Accidents","description":"Guidance for serious crashes involving commercial trucks and larger vehicles."},{"id":"mpzbwyglorkhjdkzoen","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/placeholder-motorcycle-accidents.jpg","imageId":433,"heading":"Motorcycle Accidents","description":"Support for riders facing injuries, recovery costs, and difficult insurance claims."},{"id":"mpzbxaon9jsv1sz2ly","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/placeholder-slip-fall-injuries.jpg","imageId":434,"heading":"Slip & Fall Injuries","description":"Representation for injuries caused by unsafe property conditions."},{"id":"mpzbxpgpgy7sp6glssp","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/placeholder-dog-bites.jpg","imageId":432,"heading":"Dog Bites","description":"Help for victims injured by dangerous or uncontrolled dogs."},{"id":"mpzby45w1902mknyous","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/placeholder-wrongful-death.jpg","imageId":436,"heading":"Wrongful Death","description":"Compassionate legal guidance for families after a devastating loss."}],"ctaLogoUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/05/logo-mark.svg","ctaLogoId":59} /-->

<!-- wp:mbn-theme/section-how-process-works {"steps":[{"id":"mpzjrt00cjvxblwxd5l","heading":"Reach out to us.","description":"Call or fill out the form to tell us what happened."},{"id":"mpzjs73xrznww7b6cv","heading":"Talk to an accident attorney.","description":"An experienced personal injury lawyer will hear your story, explain your options clearly, and tell you what Hastings & Hastings can do to help."},{"id":"mpzjsgy41lqwwhjyxpt","heading":"Get Clear Guidance","description":"We’ll make sure that you understand your options and move forward confidently."}],"ctaLogoUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/05/logo-mark.svg","ctaLogoId":59,"backgroundColor":"bg-light-blue"} /-->

<!-- wp:mbn-theme/section-client-testimonials {"testimonials":[{"id":"mq0tzzay44ii5g2275g","quote":" I would highly recommend Hastings and Hastings to anyone I know.","fullText":" I was in a car accident a few months ago and could not be happier with the outcome. Sean Hennick, my attorney, along with all the other staff at Hastings and Hastings, were extremely professional and helpful. Having Hastings and Hastings by my side made this process seem easy. I would highly recommend Hastings and Hastings to anyone I know.\n            ","authorName":"Verified Client","authorTitle":"Car Accident Victim","rating":5},{"id":"mq0u485p0fxsj7tug6l","quote":"It was great to not have to worry about anything.","fullText":"Hastings and Hastings is the best! Thank you so much for all the hard work you did but most of all, for just being there when I had questions. I used a different firm in my last accident (2006) and never thought I would use an attorney again. They acted nice at first but after meeting him, it was horrible. At Hastings, Sean Hennick handled my case and was awesome. Ask for him if you can... I was so scared that I might not receive the same treatment after meeting him, I could tell he knew what I was going through and was going to help. After that, their office handle pretty much everything... I could focus on getting my life back to normal. It was great to not have to worry about anything...thank you. I would recommend them and specifically Sean to anyone.","authorName":"Verified Client","authorTitle":"Car Accident Victim","rating":5},{"id":"mq0u4pbsd3qcw7m4emn","quote":"They are responsive to emails and follow up.","fullText":"They are great! They do preliminary questions to make sure that you aren't wasting your time (or theirs). They stand up for you and do what is right for you. Can't say enough positive comments on how they handled my case. They are responsive to emails and follow up. They only take legitimate cases and don't subscribe to "frivolous" lawsuits.","authorName":"Verified Client","authorTitle":"Injury Victim","rating":5},{"id":"mq0u57i6lzlducyj138","quote":"I'm so pleased with my experience with them","fullText":"I can't say how happy I am with Hastings & Hastings right now. I came to them about 9 months ago after my accident and today I received my settlement. Everyone there was very nice and helpful. My attorney's paralegal always responded to my emails quickly which really impressed me. I'm so pleased with my experience with them that I had to write a review!","authorName":"Verified Client","authorTitle":"Accident Victim","rating":5}]} /-->

<!-- wp:mbn-theme/mini-hero-section {"badgeImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-logo-hh.svg","badgeImageId":442,"videoMp4Url":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.mp4","videoMp4Id":444,"videoWebmUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.webm","videoWebmId":443,"posterImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-mini-hero-poster.jpg","posterImageId":445,"overlayImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-single-elipse-overlay.png","overlayImageId":447} /-->
EOD
	,
);
