<?php
/**
 * Page Pattern: Scottsdale
 *
 * This file contains the complete page data for the 'Scottsdale' page.
 * It can be imported to create/update the page on other environments.
 *
 * Includes: Content, Featured Image, Status, Attributes, Custom Fields
 *
 * To use: Tools → Page Content Sync → Import All Pages from Files
 *
 * @package CustomTheme
 */

return array(
	'title'               => 'Scottsdale',
	'slug'                => 'scottsdale-personal-injury-attorney',
	'status'              => 'publish',
	'excerpt'             => '',
	'parent_slug'         => '',
	'menu_order'          => 0,
	'template'            => '',
	'featured_image_url'  => '',
	'featured_image_path' => '', // Theme assets path (ships via Git)
	'custom_fields'       => array(),
	'content'             => <<<'EOD'
<!-- wp:mbn-theme/hero-section {"eyebrowText":"Locations","mainHeading":"Scottsdale Personal Injury Lawyer","subheading":"Rated as one of the best personal injury lawyers in Scottsdale, Hastings & Hastings PC provides comprehensive services to injury victims in Scottsdale, offering them one-on-one attention, proper case evaluation, and a strong negotiation style.","badgeImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-90-plus-combined-legal-experience.svg","badgeImageId":9897,"videoMp4Url":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.mp4","videoMp4Id":417,"videoWebmUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-section-more-affordable-way.webm","videoWebmId":416,"overlayImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-fg-video-overlay-1.webp","overlayImageId":9912,"showCtaBar":false,"contentJustify":"justify-between","textMaxWidth":"max-w-3xl"} /-->

<!-- wp:mbn-theme/section-location-intro {"title":"Why Choose Hastings &amp; Hastings As Your Scottsdale Personal Injury Attorney","introParagraph":"Hastings &amp; Hastings is a Phoenix personal injury law firm serving the community and the surrounding area for over 40 years with experience in litigating all common forms of personal injury law. Our compassionate team believes that those harmed by another party’s negligence or wrongdoing deserve compensation so they can focus on their recovery.","sections":[{"type":"attorneys","columnPosition":"text-left","subtitle":"Highly-Rated, Trusted Attorneys","paragraph":"Our Scottsdale law firm boasts a team of professional and experienced personal injury lawyers. We pride ourselves on being able to handle complex personal injury cases while delivering the best outcomes to our clients.","teamImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-location-hastings-attorneys.jpg","teamImageId":10769},{"type":"fee-structure","columnPosition":"badge-left","badgeImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-29-percent-diiscount.svg","badgeImageId":9916,"subtitle":"Quality Legal Services at a Discount Price","paragraph":"Our innovative approach to legal fees for accident victims means that all of our personal injury cases are handled on a contingency fee basis. We do not charge 1/3 of your settlement. Our discount fee puts more money in your pocket so that you can get back to what’s important after an accident – getting well again."},{"type":"attorneys","columnPosition":"text-left","subtitle":"Local Offices Throughout Phoenix","paragraph":"Not only do our Scottsdale personal injury lawyers enjoy a strong local reputation and valuable resources for proving your case, but we have 10 offices in the Phoenix area and the surrounding region so you can find an office close to you.","teamImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-local-offices-throughout-phoenix.jpg","teamImageId":10799}],"ctaBackgroundImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-bg-cta-column-scaled.jpg","ctaBackgroundImageId":10765,"ctaLogoUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-logo-hh.svg","ctaLogoId":442,"ctaDescription":"It’s our passion to present your case in the strongest possible terms to insurance companies and in court so you secure compensation for your damages. Call us today for a free evaluation of your personal injury case."} /-->

<!-- wp:mbn-theme/section-location-office-location {"officeLocations":[{"name":"Scottsdale Office","address":"7272 E Indian School Rd, #540, Scottsdale, AZ 85251","addressUrl":"https://www.google.com/maps?cid=584116726430625568","phoneNumber":"(480) 706-1100","phoneUrl":"tel:4807061100","byAppointmentOnly":false}]} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"backgroundColor":"bg-light-blue-100","heading":"Understanding Personal Injury Claims in Arizona","introParagraphs":["We like to feel that we are safe as we go about our daily routines, driving to work, running errands, and enjoying free time with our family. But unfortunately, accidents happen every day in Arizona, including <a href="https://azdot.gov/sites/default/files/media/2022/09/2021-crash-facts.pdf" target="_blank">120,000 car accidents</a> in 2021 alone."],"listStyle":"two-column","listItems":[{"id":"mr1fy6ldtqkxa2de88t","title":"","description":"","label":"Truck accicdents","url":"/truck-accident-lawyer/"},{"id":"mr1fycuh75piiuimzsw","title":"","description":"","label":"Motorcycle accidents","url":"/practice-areas/motorcycle-accidents/"},{"id":"mr1fyicx8aay9nm4map","title":"","description":"","label":"Bicycle Accidents","url":"/practice-areas/bicycle-accidents/"},{"id":"mr1fysighgne82wefvc","title":"","description":"","label":"Pedestrian accidents","url":"/practice-areas/phoenix-pedestrian-accident-attorney/"},{"id":"mr1fyuajn5lh0hwdlv","title":"","description":"","label":"Slip and fall incidents","url":"/practice-areas/slip-falls/"},{"id":"mr1fyzvdqjd4kofdh2","title":"","description":"","label":"Workplace accidents","url":"/phoenix-workplace-injury-attorney/"},{"id":"mr1fz502cfo4q0v73be","title":"","description":"","label":"Animal attacks","url":""}],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-how-liability-for-personal-injury.jpg","imageId":10746,"beforeListParagraphs":["Car accidents are, unfortunately, a common cause of personal injuries, but they are not the only way that accidents happen. Other significant causes of injuries in Scottsdale and throughout Arizona include the following:"],"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue-100","rows":[{"heading":"","paragraphs":["While catastrophic injuries cause the most serious economic and noneconomic damages to a victim and their family, even less grave accidents often require expensive medical treatment and lost time from work.","When an injury occurs due to another party’s negligence or reckless behavior, they are liable for compensating the victim for the life-changing physical and financial consequences. A Scottsdale personal injury attorney can help."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-location-catastropic-injuries.jpg","imageId":11188,"imagePosition":"left","id":"mr1d7lv0o5x2rc6s83p"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"heading":"Proving Liability in Arizona Personal Injury Cases","introParagraphs":["Arizona’s personal injury case law requires injury victims to prove liability. Navigating the complexities of showing liability and calculating damages can be intimidating. You need a skilled Scottsdale injury lawyer to investigate your case to prove liability and highlight the damages you’ve suffered as the direct result of another’s actions.","Our legal team’s 9 decades of combined experience in personal injury law in Scottsdale and the Phoenix area means we have the knowledge and resources to investigate your case, hear witness testimony, and hire accident reconstruction specialists if needed to prove liability."],"listItems":[{"title":"","description":"That the at-fault person owed a duty of care to protect your safety through reasonable measures, such as a driver’s duty to follow traffic laws to keep others safe on the roadway, or a hotel owner’s duty to maintain their premises to prevent safety hazards","label":"","url":"","id":"mr1cw9gv82nx7hnd8ha"},{"title":"","description":"That the person or entity at-fault breached that duty of care through their negligence or recklessness","label":"","url":"","id":"mr1cw9gvrlpsshanv4"},{"title":"","description":"That their negligence or breach of duty directly caused an injury to you","label":"","url":"","id":"mr1cw9gvq5rpoafznv"},{"id":"mr1cxgkz9sxc6700dkm","title":"","description":"That you’ve experienced significant economic and non-economic damages due to the injury","label":"","url":""}],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-location-liability-personal-injury.jpg","imageId":11190,"beforeListParagraphs":["In order to show liability in Arizona personal injury cases, the plaintiff must prove the following:"],"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue","rows":[{"heading":"","paragraphs":["Our diligent team of injury attorneys understands exactly how to collect the necessary evidence to meet this burden of proof through accident reports, medical reports, eyewitness testimony, photos and videos, and expert testimony. Hastings &amp; Hastings will strongly negotiate on your behalf with insurance companies or become a powerful voice in court if necessary to secure compensation for your damages while you focus on recovering from your injury."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-location-diligent-team.jpg","imageId":11189,"imagePosition":"left","id":"mr1d7lv0o5x2rc6s83p"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"backgroundColor":"bg-light-blue-100","heading":"Common Compensation for Damages in Arizona Personal Injury Cases","introParagraphs":["While monetary compensation can’t erase the accident that caused your injury, it can help relieve the financial burdens and other damages you’ve suffered as a result. This form of compensation also helps victims achieve a type of justice as they move forward after an accident caused by someone else. Arizona courts acknowledge both economic and non-economic damages in personal injury cases. Some examples of economic damages you may have suffered since your injury include:"],"listItems":[{"title":"","description":"Your current and future medical bills and expenses related to your injury","label":"","url":"","id":"mr1cw9gv82nx7hnd8ha"},{"title":"","description":"Financial losses from missed work and <a href="https://plaintiffmagazine.com/recent-issues/item/damages-for-loss-of-earning-capacity-what-could-have-been" target="_blank" rel="noreferrer noopener">future missed earnings </a>for ongoing treatments","label":"","url":"","id":"mr1cw9gvrlpsshanv4"},{"title":"","description":"A diminished earning potential for the future for those whose injury resulted in disability","label":"","url":"","id":"mr1cw9gvq5rpoafznv"},{"id":"mr1cxgkz9sxc6700dkm","title":"","description":"Pain and suffering","label":"","url":""},{"id":"mr1cxnzoghquz4my06","title":"","description":"Mental anguish","label":"","url":""},{"id":"mr1cxv7uhc73rtkzthq","title":"","description":"Loss of consortium (enjoying the physical aspects of relationships, such as with a romantic partner and/or the ability to support and engage in fun physical activities with children)","label":"","url":""},{"id":"mr1cy32s25x7we83no9","title":"","description":"Permanent scarring or disfigurement","label":"","url":""},{"id":"mr1esqqmzkhj5yjtv5","title":"","description":"Reduced enjoyment of life in cases of severe injury and disability","label":"","url":""}],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-location-common-compensation-damage.jpg","imageId":11186,"footerParagraphs":[]} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue-100","rows":[{"heading":"","paragraphs":["In some instances, <a href="/scottsdale-catastrophic-injury-lawyer/">catastrophic injury cases </a>may become wrongful death claims. In that case, family members deserve compensation for the devastating emotional and economic losses they suffer as a result."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-location-catastropic-injury.jpg","imageId":11185,"imagePosition":"left","id":"mr1d7lv0o5x2rc6s83p"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-text-image {"rows":[{"heading":"Will You Have to Go to Court for Your Scottsdale Personal Injury Case?","paragraphs":["Our team offers a free case evaluation, after which we begin strategizing a plan for your compensation. In most cases, our strong community resources, local reputation, and investigative skills are enough to make a very compelling case during negotiations with the liable party’s insurance carrier, typically resulting in a settlement without the need for court litigation."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-how-hastings-n-hastings-can-help.jpg","imageId":10741,"imagePosition":"right","id":"mr1eil79qhm345ui5cd"},{"heading":"","paragraphs":["However, our decades of experience in Arizona courts means we are more than ready to advocate on your behalf in a courtroom to gain a positive jury verdict and compensation for your damages if required. You deserve to recoup some of the losses you’ve suffered as a direct result of your injury so you can move forward."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-statute-of-limitation.jpg","imageId":10736,"imagePosition":"left","id":"mr1eil79r1uuk1fd5nd"}]} /-->

<!-- wp:mbn-theme/section-location-heading-list-image {"backgroundColor":"bg-light-blue-100","heading":"What Can a Scottsdale Personal Injury Lawyer Do For You?","introParagraphs":["A Scottsdale personal injury lawyer with a strong local reputation in the community can represent your interests by collecting and examining the following evidence in order to craft a compelling case:"],"listItems":[{"title":"","description":"The police report of your accident or an accident or incident report","label":"","url":"","id":"mr1cw9gv82nx7hnd8ha"},{"title":"","description":"Your medical records and bills","label":"","url":"","id":"mr1cw9gvrlpsshanv4"},{"title":"","description":"Your pay prior to the accident and employer evidence of your lost time from work","label":"","url":"","id":"mr1cw9gvq5rpoafznv"},{"id":"mr1cxgkz9sxc6700dkm","title":"","description":"Photos and/or video of the accident or incident if any exist","label":"","url":""},{"id":"mr1cxnzoghquz4my06","title":"","description":"Interview eyewitnesses","label":"","url":""},{"id":"mr1cxv7uhc73rtkzthq","title":"","description":"The testimony of expert witnesses, including medical experts and accident reconstruction experts","label":"","url":""},{"id":"mr1cy32s25x7we83no9","title":"","description":"Interview family members about the injury’s impact on your quality of life","label":"","url":""}],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/07/img-location-billing-statement.jpg","imageId":11174,"footerParagraphs":[],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-text-image {"backgroundColor":"bg-light-blue-100","rows":[{"heading":"","paragraphs":["At Hastings &amp; Hastings, we believe in providing compassionate, individualized attention with updates throughout every step of the progress in your case as we <a href="https://www.hg.org/legal-articles/evidence-to-preserve-after-a-car-accident-32402" data-type="link" data-id="https://www.hg.org/legal-articles/evidence-to-preserve-after-a-car-accident-32402">collect evidence</a>, show clear liability, and negotiate with insurance companies to secure compensation for your damages."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-location-peoria-can-be-held-liable-for-personal-injury.jpg","imageId":10860,"imagePosition":"left","id":"mr1h6vd02unvtjh1ycr"}],"className":"pt-40"} /-->

<!-- wp:mbn-theme/section-location-text-image {"rows":[{"heading":"Why Choose Us to Represent Your Interests in a Personal Injury Case?","paragraphs":["Not only do our Scottsdale personal injury lawyers enjoy a strong local reputation and valuable resources for proving your case, but we have 10 offices in the Phoenix area and the surrounding region so you can find an office close to you.","Our <a href="/scottsdale-car-accident-attorney/">Scottsdale car accident attorneys</a> offer free evaluations, work at discounted rates, and operate on a contingency fee basis so we get paid only when you get a substantial payout on your claim.","Our decades of experience in all forms of personal injury cases put us in the best position to understand your case, provide the investigative skills you need, and diligently file all paperwork in a timely manner within the state’s 2-year statute of limitations."],"listStyle":"single","listItems":[],"paragraphsAfterList":[],"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-statute-of-limitation-2.jpg","imageId":10858,"imagePosition":"right","id":"mr1chv0mljb61ek38u"}]} /-->

<!-- wp:mbn-theme/section-location-cta-card-badges {"ctaTitle":"Need a Personal Injury Lawyer in Scottsdale, AZ?","ctaDescription":"If you or a loved one has been injured due to someone else’s reckless actions, immediate legal assistance is crucial. At Hastings & Hastings, we work on a contingency fee basis, meaning we do not get paid unless you win. Let our experienced Scottsdale personal injury lawyers help you secure the compensation you deserve.","ctaButtonText":"Request Free Consultation","ctaBackgroundImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/img-cta-card-bg-scaled.jpg","ctaBackgroundImageId":10723,"ctaLogoImageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-logo-hh.svg","ctaLogoImageId":442,"badgesTextParagraphs":[{"id":1,"text":"We guarantee that you will speak with a licensed Arizona attorney at your initial consultation."},{"id":"mr1c4lkebfnzal5ldnd","text":"If we’re able to take your case, we’ll pursue compensation on your behalf in the maximum amount possible, and our experience and client testimonials make that clear. Our Discount Fee arrangement demonstrates our clear commitment to putting our clients first. Let us help you or your loved one with a personal injury case."}],"badgesItems":[{"id":1,"imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-90-plus-combined-legal-experience-blck.svg","imageId":10028,"imageFallback":"","imageAlt":"90+ Combined Legal Experience","imageWidth":303,"imageHeight":303},{"id":"mr1c4zebrktube3ghp","imageUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/badge-29-percent-diiscount.svg","imageId":9916,"imageFallback":"","imageAlt":"29% Fee — Discount Accident Lawyers badge","imageWidth":214,"imageHeight":214}]} /-->

<!-- wp:block {"ref":10773} /-->

<!-- wp:mbn-theme/section-video-bg-form {"videoMp4Url":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.mp4","videoWebmUrl":"http://hastingsandhastings.dev.local/wp-content/uploads/2026/06/vid-breathtaking-and-beautiful-view-of-phoenix-az.webm","gravityFormId":"4","align":"full"} /-->
EOD
	,
);
